apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app
  namespace: microservices
  labels:
    app: inventory-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-app
  template:
    metadata:
      labels:
        app: inventory-app
    spec:
      containers:
      - name: inventory-app
        image: emanmahfoodh/inventory-app:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: postgres-password
        - name: INVENTORY_DB_NAME
          valueFrom:
            secretKeyRef:
              name: database-config
              key: inventory-db-name
        - name: DATABASE_URI
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@inventory-db:5432/$(INVENTORY_DB_NAME)"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8080"
        - name: DEBUG
          value: "false"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-app
  namespace: microservices
  labels:
    app: inventory-app
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: inventory-app
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: inventory-app-hpa
  namespace: microservices
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inventory-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15