apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: microservices
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management-alpine
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: rabbitmq-user
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: rabbitmq-password
        # Updated health checks with more reasonable settings
        livenessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - status
          initialDelaySeconds: 120  # Wait 2 minutes before first check
          periodSeconds: 30         # Check every 30 seconds
          timeoutSeconds: 15        # Wait 15 seconds for response
          failureThreshold: 5       # Allow 5 failures before restart
        readinessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - ping
          initialDelaySeconds: 30   # Wait 30 seconds before first check
          periodSeconds: 10         # Check every 10 seconds
          timeoutSeconds: 10        # Wait 10 seconds for response
          failureThreshold: 3       # Allow 3 failures before marking unready
        # Add startup probe to handle slow startup
        startupProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - ping
          initialDelaySeconds: 10   # Start checking after 10 seconds
          periodSeconds: 10         # Check every 10 seconds
          timeoutSeconds: 10        # Wait 10 seconds for response
          failureThreshold: 18      # Allow up to 3 minutes for startup (18 * 10s)
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"           # Increased memory limit
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: microservices
  labels:
    app: rabbitmq
spec:
  ports:
  - port: 5672
    targetPort: 5672
    name: amqp
  - port: 15672
    targetPort: 15672
    name: management
  selector:
    app: rabbitmq