apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: microservices
type: Opaque
stringData:
  postgres-user: postgres
  postgres-password: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: microservices
type: Opaque
stringData:
  rabbitmq-user: guest
  rabbitmq-password: guest
---
apiVersion: v1
kind: Secret
metadata:
  name: database-config
  namespace: microservices
type: Opaque
stringData:
  inventory-db-name: movies_db
  billing-db-name: billing_db
  rabbitmq-queue: billing_queue
